spring:
  application:
    name: first-grab
  profiles:
    default: local

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC

