spring:
  application:
    name: first-grab
  profiles:
    default: local

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC

jwt:
  access-token-secret: ${JWT_ACCESS_SECRET}
  refresh-token-secret: ${JWT_REFRESH_SECRET}
  access-token-expiration: 1800000
  refresh-token-expiration: 1209600000

